# 系统主配置文件

# 系统设置
system:
  name: "PP量化交易系统"
  version: "1.0.0"
  debug: false
  timezone: "Asia/Shanghai"

# 数据源配置
data_sources:
  tushare:
    token: "${TUSHARE_TOKEN}"
    timeout: 30
  akshare:
    timeout: 30
  ccxt:
    timeout: 30
    rate_limit: true

# 数据库配置
database:
  postgresql:
    host: "localhost"
    port: 5432
    database: "pp_quant"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: "${REDIS_PASSWORD}"

# 交易配置
trading:
  # 模拟交易配置
  paper_trading:
    initial_capital: 1000000
    commission_rate: 0.0003
    slippage: 0.0001
  
  # 实盘交易配置
  real_trading:
    enabled: false
    brokers:
      xtp:
        enabled: false
        account: "${XTP_ACCOUNT}"
        password: "${XTP_PASSWORD}"
      binance:
        enabled: false
        api_key: "${BINANCE_API_KEY}"
        api_secret: "${BINANCE_API_SECRET}"

# 风控配置
risk_management:
  position_limit: 0.8  # 最大仓位比例
  single_position_limit: 0.2  # 单个品种最大仓位比例
  stop_loss: 0.1  # 止损比例
  take_profit: 0.2  # 止盈比例
  max_drawdown: 0.2  # 最大回撤限制

# 回测配置
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 1000000
  commission_rate: 0.0003
  slippage: 0.0001

# 日志配置
logging:
  level: "INFO"
  file: "logs/pp_quant.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 9090
  alert:
    enabled: true
    email:
      smtp_server: "smtp.example.com"
      smtp_port: 587
      username: "${ALERT_EMAIL_USER}"
      password: "${ALERT_EMAIL_PASSWORD}"
      recipients: ["alert@example.com"] 